### PR TITLE
Animations: donate button

### PR DESCRIPTION
**Pull request by jzhzhang66**
This PR contains code for the hover state of the donate button.

### CODE REVIEW

**Comment by jean-zhang** [comment]
bizarrely, after I click the button and the animation begins, it's much harder to scroll on my phone? and a small black bar shows up on the middle/bottom

**Comment by jean-zhang** [comment]
found the issue -- the SVGs are slightly off from one another, I just created a new one based on the old one so that they match exactly, pushing up the changes now!

**Review by jean-zhang — APPROVED** [review]
<3

**Review by isabellberzsenyi — APPROVED** [review]
art

**Pull request merged**
