### PR TITLE
Hi-fi: About- Mission and Values Section

### LINKED ISSUE #32: Lo-fi: About Page

### PR DESCRIPTION
**Pull request by isabellberzsenyi**
This PR contains:
- Minor styling changes to the ImageBoxLink component (adding a height prop)
- Create About Mission section and styling
> - Including helper component for the more resources button
- Create About Values section and styling
> - Including helper component for the separate values rendered
- Putting the whole About page together

** Note the About Founder PR is rebased onto this branch (hence the first 5 commits are from that branch) but those changes are on a separate PR **

### CODE REVIEW

**Comment by jean-zhang** [comment]
This was on my large monitor
Screen Shot 2021-05-04 at 5 29 31 PM

Also the gap seems very large on mobile/tablet
IMG_A761BA48AD7B-1

**Review by jzhzhang66 — CHANGES_REQUESTED** [review]
Add object-fit: cover so it doesn't stretch
image

**Review by jzhzhang66 — CHANGES_REQUESTED** [review]
Can we add in some top margin / padding so the box link is centered
image

**Review by jzhzhang66 — COMMENTED** [review]
What do you think about aligning all the spark arrows to be in line with the first one? In the hi-fis they're slighly off but I kind of feel like it would look better if they were all aligned because the unalignment seems kind of unintentional to me
image

**Review by jzhzhang66 — CHANGES_REQUESTED** [review]
Remove this large space on ipad
image

**Review by jzhzhang66 — CHANGES_REQUESTED** [review]
These spaces seem smaller on the hi-fis could we make them slightly smaller? 
image
image

**Review by josephmannis — COMMENTED** [review]
Code looks good! Note that scrolling animation doesn't work on Safari. Not sure if you want to fix that here or in another PR since it seems to be a cross-pr issue.

**Comment by isabellberzsenyi** [comment]
@josephmannis will take care of the scroll animation in a separate pr thanks for the catch!

**Review by jzhzhang66 — CHANGES_REQUESTED** [review]
Can we reduce this spacing a bit on desktop?
image
image

**Review by jzhzhang66 — CHANGES_REQUESTED** [review]
Something funkys happening with the values header on mobile
image

**Review by jzhzhang66 — COMMENTED** [review]
There seems to be more padding between the 2nd and 3rd value could we double check its the same
image

**Review by jzhzhang66 — CHANGES_REQUESTED** [review]
spark arrow doesn't scroll when clicked
image

**Pull request merged**
