### PR TITLE
Bug Fix: CTA Spark Arrow

### PR DESCRIPTION
**Pull request by isabellberzsenyi**
This PR adds animation to Spark Arrow on Desktop sizes.
Please double check all locations of the spark arrow for placement and movement and functionality

### CODE REVIEW

**Comment by jean-zhang** [comment]
still a draft?

**Review by jzhzhang66 — COMMENTED** [review]
Since the arrow is a lot longer now and we have enough space, can we make the text and arrow start at the same spot 
image

**Review by jzhzhang66 — COMMENTED** [review]
When animating, can the arrow go down a tiny bit further? Also idk if this is possible but could we make it faster / the duration shorter? Most of the arrows on the site move pretty swiftly so lets match that if possible

**Review by jean-zhang — APPROVED** [review]

**Review by jzhzhang66 — APPROVED** [review]
BEAUT

**Pull request merged**
