### PR TITLE
Reusable component: Quote Carousel

### PR DESCRIPTION
**Pull request by isabellberzsenyi**
This PR contains code for the quote carousel at the end of the page on the **About** and **Story Inquiry** pages. Please note a lot of the code for the arches is similar to the ArchModal, yet different enough that the components were not reused. 

**Video attached to show functionality since about page and story inquiry pages are not done**
[Video Here](https://drive.google.com/file/d/1MXtNUPiTeyxxYBK82yItBHZ4OA-5OpI7/view?usp=sharing)

How to use: Quotes should be an array of strings

```
const getQuotes = theAlleywayNamesMeaning.map((m) => {
    return getString(m.meaning);
  });

const quoteCarouselData = {
    title: theAlleywayNamesTitle,
    description: theAlleywayNamesDescription,
    quotes: getQuotes,
    quoteImage: theAlleywayNamesImage,
  };

<QuoteCarousel quoteCarouselData={quoteCarouselData} />
```

### CODE REVIEW

**Review by jzhzhang66 — CHANGES_REQUESTED** [review]
From screen width 500 - 1000 it looks slightlyyy off centered- could we move all the text / arch stuff like maybe 1 or 2 em to the right?

**Review by jzhzhang66 — CHANGES_REQUESTED** [review]
On screen widths smaller than the desktop, the star doesn't seem centered - could we move it to the left a bit to center it? 

Also maybe make the star a bit bigger since it seems bigger on the hi-fis

**Review by jean-zhang — APPROVED** [review]
lgtm!

**Review by jzhzhang66 — APPROVED** [review]
Looks good!!!

**Pull request merged**
